# Generated by Django 6.0.4 on 2026-04-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_apikeyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='can_create_order',
            field=models.BooleanField(default=True),
        ),
    ]
