# Generated by Django 6.0.4 on 2026-04-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_webhook_failedwebhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedwebhook',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
