# Generated by Django 6.0.4 on 2026-05-02 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_failedwebhook_next_retry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='secret',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
