# Generated by Django 6.0.4 on 2026-05-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_cost_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
