# Generated by Django 6.0.4 on 2026-05-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='event_type',
            field=models.CharField(choices=[('stock.low', 'Low Stock')], max_length=50),
        ),
    ]
