# Generated by Django 6.0.4 on 2026-05-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_rule_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('stock.low', 'Low Stock')], max_length=50),
        ),
    ]
