# Generated by Django 6.0.4 on 2026-05-20 03:15

from django.db import migrations, models


def backfill_user_category_and_roles(apps, schema_editor):
    User = apps.get_model("authentication", "User")

    User.objects.filter(role="staff").update(role="employee")
    User.objects.filter(tenant__isnull=True).update(user_type="system")
    User.objects.filter(tenant__isnull=False).update(user_type="tenant")


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('system', 'System'), ('tenant', 'Tenant')], db_index=True, default='tenant', max_length=20),
        ),
        migrations.RunPython(
            backfill_user_category_and_roles,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], default='admin', max_length=20),
        ),
    ]
